// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Authentication state enum
enum AuthState {
  notAuthenticated,
  loading,
  authenticated,
  error,
}

/// User profile structure
class UserProfile {
  final KeypairResponse keypair;
  final ProfileMetadata? metadata;
  final bool isLoggedIn;

  const UserProfile({
    required this.keypair,
    this.metadata,
    required this.isLoggedIn,
  });

  @override
  int get hashCode => keypair.hashCode ^ metadata.hashCode ^ isLoggedIn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          runtimeType == other.runtimeType &&
          keypair == other.keypair &&
          metadata == other.metadata &&
          isLoggedIn == other.isLoggedIn;
}

/// Response for generated keypair
class KeypairResponse {
  final String publicKey;
  final String secretKey;
  final String npub;
  final String nsec;

  const KeypairResponse({
    required this.publicKey,
    required this.secretKey,
    required this.npub,
    required this.nsec,
  });

  Map<String, dynamic> toJson() => {
    'publicKey': publicKey,
    'secretKey': secretKey,
    'npub': npub,
    'nsec': nsec,
  };

  factory KeypairResponse.fromJson(Map<String, dynamic> json) => KeypairResponse(
    publicKey: json['publicKey'] as String,
    secretKey: json['secretKey'] as String,
    npub: json['npub'] as String,
    nsec: json['nsec'] as String,
  );

  @override
  int get hashCode => publicKey.hashCode ^ secretKey.hashCode ^ npub.hashCode ^ nsec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeypairResponse &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          secretKey == other.secretKey &&
          npub == other.npub &&
          nsec == other.nsec;
}

/// Response for parsed Nostr URI
class NostrUriResponse {
  final String uriType;
  final String data;
  final String bech32;

  const NostrUriResponse({
    required this.uriType,
    required this.data,
    required this.bech32,
  });

  @override
  int get hashCode => uriType.hashCode ^ data.hashCode ^ bech32.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NostrUriResponse &&
          runtimeType == other.runtimeType &&
          uriType == other.uriType &&
          data == other.data &&
          bech32 == other.bech32;
}

/// Profile metadata structure
class ProfileMetadata {
  final String name;
  final String? displayName;
  final String? about;
  final String? picture;
  final String? website;
  final String? nip05;
  final String? lud16;

  const ProfileMetadata({
    required this.name,
    this.displayName,
    this.about,
    this.picture,
    this.website,
    this.nip05,
    this.lud16,
  });

  Map<String, dynamic> toJson() => {
    'name': name,
    'displayName': displayName,
    'about': about,
    'picture': picture,
    'website': website,
    'nip05': nip05,
    'lud16': lud16,
  };

  factory ProfileMetadata.fromJson(Map<String, dynamic> json) => ProfileMetadata(
    name: json['name'] as String,
    displayName: json['displayName'] as String?,
    about: json['about'] as String?,
    picture: json['picture'] as String?,
    website: json['website'] as String?,
    nip05: json['nip05'] as String?,
    lud16: json['lud16'] as String?,
  );

  @override
  int get hashCode =>
      name.hashCode ^
      displayName.hashCode ^
      about.hashCode ^
      picture.hashCode ^
      website.hashCode ^
      nip05.hashCode ^
      lud16.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileMetadata &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          displayName == other.displayName &&
          about == other.about &&
          picture == other.picture &&
          website == other.website &&
          nip05 == other.nip05 &&
          lud16 == other.lud16;
}

/// Response for signed message/event
class SignedMessageResponse {
  final String id;
  final String pubkey;
  final BigInt createdAt;
  final BigInt kind;
  final List<List<String>> tags;
  final String content;
  final String sig;

  const SignedMessageResponse({
    required this.id,
    required this.pubkey,
    required this.createdAt,
    required this.kind,
    required this.tags,
    required this.content,
    required this.sig,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pubkey.hashCode ^
      createdAt.hashCode ^
      kind.hashCode ^
      tags.hashCode ^
      content.hashCode ^
      sig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignedMessageResponse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pubkey == other.pubkey &&
          createdAt == other.createdAt &&
          kind == other.kind &&
          tags == other.tags &&
          content == other.content &&
          sig == other.sig;
}
